server:
  port: 8020
  
spring:
  application:
    name: customer-user
    
eureka:
  client:
    register-with-eureka: false    #不会将自己的信息注册到eureka中
    service-url:                 #链接注册中心集群
       defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: customer-user-8020                #定义微服务的名称多个服务id必须不同
    prefer-ip-address: true  #是否显示IP和端口
    
feign:
  hystrix:
    enabled: true         # #启动熔断器机制 !!!!!!!!!!!!!